package com.example.datn_realeaste_crm.security;

/**
 * Enum representing all available permissions in the system
 */
public enum PermissionEnum {
    // User management
    USER_VIEW_ALL,
    USER_VIEW_DEPARTMENT,
    USER_VIEW_OWN,
    USER_CREATE,
    USER_UPDATE_ALL,
    USER_UPDATE_DEPARTMENT,
    USER_UPDATE_OWN,
    USER_DELETE,
    USER_ACTIVATE_DEACTIVATE,
    USER_ASSIGN_ROLE,

    // Department management
    DEPARTMENT_VIEW_ALL,
    DEPARTMENT_CREATE,
    DEPARTMENT_UPDATE,
    DEPARTMENT_DELETE,
    DEPARTMENT_ASSIGN_MANAGER,

    // Property management
    PROPERTY_VIEW_ALL,
    PROPERTY_VIEW_DEPARTMENT,
    PROPERTY_VIEW_ASSIGNED,
    PROPERTY_VIEW_OWNED,
    PROPERTY_CREATE,
    PROPERTY_UPDATE_ALL,
    PROPERTY_UPDATE_DEPARTMENT,
    PROPERTY_UPDATE_ASSIGNED,
    PROPERTY_UPDATE_OWNED,
    PROPERTY_DELETE,
    PROPERTY_APPROVE,
    PROPERTY_REJECT,
    PROPERTY_ASSIGN,

    // Customer management
    CUSTOMER_VIEW_ALL,
    CUSTOMER_VIEW_DEPARTMENT,
    CUSTOMER_VIEW_ASSIGNED,
    CUSTOMER_CREATE,
    CUSTOMER_UPDATE_ALL,
    CUSTOMER_UPDATE_DEPARTMENT,
    CUSTOMER_UPDATE_ASSIGNED,
    CUSTOMER_DELETE,
    CUSTOMER_ASSIGN,

    // Interaction management
    INTERACTION_VIEW_ALL,
    INTERACTION_VIEW_DEPARTMENT,
    INTERACTION_VIEW_OWN,
    INTERACTION_VIEW_PROPERTY_RELATED,
    INTERACTION_CREATE,
    INTERACTION_UPDATE_ALL,
    INTERACTION_UPDATE_OWN,
    INTERACTION_DELETE,

    // Appointment management
    APPOINTMENT_VIEW_ALL,
    APPOINTMENT_VIEW_DEPARTMENT,
    APPOINTMENT_VIEW_OWN,
    APPOINTMENT_VIEW_PROPERTY_RELATED,
    APPOINTMENT_CREATE,
    APPOINTMENT_UPDATE_ALL,
    APPOINTMENT_UPDATE_OWN,
    APPOINTMENT_DELETE,
    APPOINTMENT_CONFIRM_REJECT,

    // Report management
    REPORT_VIEW_ALL,
    REPORT_VIEW_DEPARTMENT,
    REPORT_EXPORT,

    // District management
    DISTRICT_VIEW,
    DISTRICT_CREATE,
    DISTRICT_UPDATE,
    DISTRICT_DELETE,

    // Audit logs
    AUDIT_LOG_VIEW,

    // System configuration
    SYSTEM_CONFIG_MANAGE
}